on:
  pull_request:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Read result ED
        id: resultOutput
        uses: estartandodevs-course/capture-test-result-action@v1.0.0
      - name: Test Evaluator ED
        id: evaluator
        uses: estartandodevs-course/evaluator-action@v1.0.2
        with:
          testResults: ${{ steps.resultOutput.outputs.resultOfOutputTests }}

      - name: Create comment with evaluation result
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.evaluator.outputs.report }}
